version: "3.9"

services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - duma_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  duma_data:
